provider:
  name: aws
  runtime: go1.x
  lambdaHashingVersion: 20201221

package:
  patterns:
    - "!./**"
    - ./bin/**

functions:
  graphql:
    handler: bin/server
    events:
      - http: ANY /{proxy+}
      - http: ANY /