// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	scalars "github.com/cobyforrester/image-transform/schema"
)

type ImageInstructions struct {
	Image scalars.Image `json:"image"`
	Tint  *bool         `json:"tint"`
}

type ImageJSON struct {
	Base64  string        `json:"base64"`
	Options *ImageOptions `json:"options"`
}

type ImageJSONInput struct {
	Image *ImageJSON `json:"image"`
}

type ImageOptions struct {
	Blur      *string `json:"blur"`
	Scale     *string `json:"scale"`
	Grayscale *bool   `json:"grayscale"`
	Invert    *bool   `json:"invert"`
	Rotate    *string `json:"rotate"`
}
