// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	scalars "github.com/cobyforrester/serve-example/schema"
)

type ImageInstructions struct {
	Image scalars.Image `json:"image"`
	Tint  *bool         `json:"tint"`
}
